// Code generated by _tmpl/utils.h.tmpl. DO NOT EDIT.

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// clang-format off
//go:build driverlib
// clang-format on

#pragma once

#include "adbc.h"
#include <stdlib.h>

struct AdbcError* TrinoErrorFromArrayStream(struct ArrowArrayStream*, AdbcStatusCode*);
AdbcStatusCode TrinoDatabaseGetOption(struct AdbcDatabase*, const char*, char*, size_t*, struct AdbcError*);
AdbcStatusCode TrinoDatabaseGetOptionBytes(struct AdbcDatabase*, const char*, uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode TrinoDatabaseGetOptionDouble(struct AdbcDatabase*, const char*, double*, struct AdbcError*);
AdbcStatusCode TrinoDatabaseGetOptionInt(struct AdbcDatabase*, const char*, int64_t*, struct AdbcError*);
AdbcStatusCode TrinoDatabaseInit(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode TrinoDatabaseNew(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode TrinoDatabaseRelease(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode TrinoDatabaseSetOption(struct AdbcDatabase* db, const char* key, const char* value, struct AdbcError* err);
AdbcStatusCode TrinoDatabaseSetOptionBytes(struct AdbcDatabase*, const char*, const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode TrinoDatabaseSetOptionDouble(struct AdbcDatabase*, const char*, double, struct AdbcError*);
AdbcStatusCode TrinoDatabaseSetOptionInt(struct AdbcDatabase*, const char*, int64_t, struct AdbcError*);

AdbcStatusCode TrinoConnectionCancel(struct AdbcConnection*, struct AdbcError*);
AdbcStatusCode TrinoConnectionCommit(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode TrinoConnectionGetInfo(struct AdbcConnection* cnxn, const uint32_t* codes, size_t len, struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode TrinoConnectionGetObjects(struct AdbcConnection* cnxn, int depth, const char* catalog, const char* dbSchema, const char* tableName, const char** tableType, const char* columnName, struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode TrinoConnectionGetOption(struct AdbcConnection*, const char*, char*, size_t*, struct AdbcError*);
AdbcStatusCode TrinoConnectionGetOptionBytes(struct AdbcConnection*, const char*, uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode TrinoConnectionGetOptionDouble(struct AdbcConnection*, const char*, double*, struct AdbcError*);
AdbcStatusCode TrinoConnectionGetOptionInt(struct AdbcConnection*, const char*, int64_t*, struct AdbcError*);
AdbcStatusCode TrinoConnectionGetStatistics(struct AdbcConnection*, const char*, const char*, const char*, char, struct ArrowArrayStream*, struct AdbcError*);
AdbcStatusCode TrinoConnectionGetStatisticNames(struct AdbcConnection*, struct ArrowArrayStream*, struct AdbcError*);
AdbcStatusCode TrinoConnectionGetTableSchema(struct AdbcConnection* cnxn, const char* catalog, const char* dbSchema, const char* tableName, struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode TrinoConnectionGetTableTypes(struct AdbcConnection* cnxn, struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode TrinoConnectionInit(struct AdbcConnection* cnxn, struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode TrinoConnectionNew(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode TrinoConnectionReadPartition(struct AdbcConnection* cnxn, const uint8_t* serialized, size_t serializedLen, struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode TrinoConnectionRelease(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode TrinoConnectionRollback(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode TrinoConnectionSetOption(struct AdbcConnection* cnxn, const char* key, const char* val, struct AdbcError* err);
AdbcStatusCode TrinoConnectionSetOptionBytes(struct AdbcConnection*, const char*, const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode TrinoConnectionSetOptionDouble(struct AdbcConnection*, const char*, double, struct AdbcError*);
AdbcStatusCode TrinoConnectionSetOptionInt(struct AdbcConnection*, const char*, int64_t, struct AdbcError*);

AdbcStatusCode TrinoStatementBind(struct AdbcStatement* stmt, struct ArrowArray* values, struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode TrinoStatementBindStream(struct AdbcStatement* stmt, struct ArrowArrayStream* stream, struct AdbcError* err);
AdbcStatusCode TrinoStatementCancel(struct AdbcStatement*, struct AdbcError*);
AdbcStatusCode TrinoStatementExecuteQuery(struct AdbcStatement* stmt, struct ArrowArrayStream* out, int64_t* affected, struct AdbcError* err);
AdbcStatusCode TrinoStatementExecutePartitions(struct AdbcStatement* stmt, struct ArrowSchema* schema, struct AdbcPartitions* partitions, int64_t* affected, struct AdbcError* err);
AdbcStatusCode TrinoStatementExecutePartitionsTrampoline(struct AdbcStatement* stmt, struct ArrowSchema* schema, struct AdbcPartitions* partitions, int64_t* affected, struct AdbcError* err);
AdbcStatusCode TrinoStatementExecuteSchema(struct AdbcStatement*, struct ArrowSchema*, struct AdbcError*);
AdbcStatusCode TrinoStatementGetOption(struct AdbcStatement*, const char*, char*, size_t*, struct AdbcError*);
AdbcStatusCode TrinoStatementGetOptionBytes(struct AdbcStatement*, const char*, uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode TrinoStatementGetOptionDouble(struct AdbcStatement*, const char*, double*, struct AdbcError*);
AdbcStatusCode TrinoStatementGetOptionInt(struct AdbcStatement*, const char*, int64_t*, struct AdbcError*);
AdbcStatusCode TrinoStatementGetParameterSchema(struct AdbcStatement* stmt, struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode TrinoStatementNew(struct AdbcConnection* cnxn, struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode TrinoStatementPrepare(struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode TrinoStatementRelease(struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode TrinoStatementSetOption(struct AdbcStatement* stmt, const char* key, const char* value, struct AdbcError* err);
AdbcStatusCode TrinoStatementSetOptionBytes(struct AdbcStatement*, const char*, const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode TrinoStatementSetOptionDouble(struct AdbcStatement*, const char*, double, struct AdbcError*);
AdbcStatusCode TrinoStatementSetOptionInt(struct AdbcStatement*, const char*, int64_t, struct AdbcError*);
AdbcStatusCode TrinoStatementSetSqlQuery(struct AdbcStatement* stmt, const char* query, struct AdbcError* err);
AdbcStatusCode TrinoStatementSetSubstraitPlan(struct AdbcStatement* stmt, const uint8_t* plan, size_t length, struct AdbcError* err);

AdbcStatusCode AdbcDriverTrinoInit(int version, void* rawDriver, struct AdbcError* err);

static inline void TrinoerrRelease(struct AdbcError* error) {
  if (error->release) {
    error->release(error);
    error->release = NULL;
  }
}

void Trino_release_error(struct AdbcError* error);

struct TrinoError {
  char* message;
  char** keys;
  uint8_t** values;
  size_t* lengths;
  int count;
};

void TrinoReleaseErrWithDetails(struct AdbcError* error);

int TrinoErrorGetDetailCount(const struct AdbcError* error);
struct AdbcErrorDetail TrinoErrorGetDetail(const struct AdbcError* error, int index);

int TrinoArrayStreamGetSchemaTrampoline(struct ArrowArrayStream* stream, struct ArrowSchema* out);
int TrinoArrayStreamGetNextTrampoline(struct ArrowArrayStream* stream, struct ArrowArray* out);
